[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[tool.coverage.run]
source = ["src/"]
branch = true
omit = ["*tests*", ".tox/**", "venv/**", "setup.py"]
command_line = "-m pytest tests/"
