version: 2.1

orbs:
  python: circleci/python@1.4.0
  codecov: codecov/codecov@1.2.2

jobs:
  build-and-test:
    executor: python/default
    working_directory: ~/dicom_parser
    docker:
      - image: themattrix/tox
    steps:
      - checkout
      - run:
          name: Install libmagic
          command: |
            apt update
            apt install -y libmagic1
      - run:
          name: Upgrade pip version
          command: pip install -U pip
      - run:
          name: Install package
          command: pip install .[all]
      - run:
          name: Install tox
          command: pip install tox
      - run:
          name: Test using tox
          command: tox
      - codecov/upload:
          file: coverage.xml
          flags: unittests

workflows:
  main:
    jobs:
      - build-and-test
