version: 2.1

orbs:
  python: circleci/python@0.3.0
  codecov: codecov/codecov@1.0.5

jobs:
  build-and-test:
    working_directory: ~/dicom_parser
    docker:
      - image: themattrix/tox
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          name: Install libmagic
          command: sudo apt-get update && sudo apt-get install libmagic1
      - run:
          name: Install tox
          command: pip install tox
      - run:
          name: Test using tox
          command: tox
      - codecov/upload:
          file: coverage.xml
          flags: unittests

workflows:
  main:
    jobs:
      - build-and-test
